export { send_email } from './client'
export { welcome_template } from './templates/welcome'
export { budget_alert_template } from './templates/budget-alert'
export { monthly_report_template } from './templates/monthly-report'
export type { MonthlyReportData } from './templates/monthly-report'
export { weekly_summary_template } from './templates/weekly-summary'
export type { WeeklySummaryData } from './templates/weekly-summary'
export { low_activity_template } from './templates/low-activity'
export type { LowActivityData } from './templates/low-activity'
