export { send_email } from './client'
export type { EmailAttachment } from './client'
export { recurring_fired_template } from './templates/recurring-fired'
export type { RecurringFiredData } from './templates/recurring-fired'
export { export_ready_template } from './templates/export-ready'
export type { ExportReadyData } from './templates/export-ready'
export { welcome_template } from './templates/welcome'
export { budget_alert_template } from './templates/budget-alert'
export { monthly_report_template } from './templates/monthly-report'
export type { MonthlyReportData } from './templates/monthly-report'
export { weekly_summary_template } from './templates/weekly-summary'
export type { WeeklySummaryData } from './templates/weekly-summary'
export { low_activity_template } from './templates/low-activity'
export type { LowActivityData } from './templates/low-activity'
